name: Build DiasOrganize APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Analisar projeto
        run: flutter analyze

      - name: Executar testes
        run: flutter test

          name: DiasOrganize-v2-debug-apk
        run: flutter test

      - name: Construir APK (Debug)
        run: flutter build apk --debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: DiasOrganize-v2-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
